# Generated by Django 4.2.11 on 2024-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formula", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.TextField(unique=True, verbose_name="username"),
        ),
    ]
