# Generated by Django 4.2.11 on 2024-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formula", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True, verbose_name="username"),
        ),
    ]
