# Generated by Django 2.2.28 on 2024-03-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
