# Generated by Django 2.2.28 on 2024-03-22 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_auto_20240322_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 52, 24, 433985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 52, 24, 433985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 52, 24, 433985, tzinfo=utc), null=True),
        ),
    ]
