# Generated by Django 2.2.28 on 2024-03-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_user_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='teamlead',
            table='Team Lead',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='Team Member',
        ),
    ]
