# Generated by Django 4.2.11 on 2024-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formula", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(blank=True, upload_to="profile_images"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
