# Generated by Django 4.2.11 on 2024-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_customuser_bio_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
