# Generated by Django 2.2.28 on 2024-03-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0005_auto_20240307_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(choices=[('GE', 'General'), ('OP', 'Operations'), ('EV', 'Electric Vehicle')], default='GE', max_length=64),
        ),
    ]
