# Generated by Django 2.2.28 on 2024-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0007_auto_20240313_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
