# Generated by Django 2.2.28 on 2024-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_auto_20240314_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
